import React from "react";
import { Link } from "react-router-dom";
import { Star, Clock, Users, BookOpen, ArrowRight } from "lucide-react";
import { ROUTES } from "../../constants/routes"; // Add this import

export default function CourseCard({ course }) {
  // Use the ID generated by the Safety Mapper
  const id = course._id || course.id;
  
  // Safety Mappers
  const students = course.totalStudents || course.students || 0;
  const rating = course.averageRating || course.rating || 0;
  const reviews = course.totalReviews || course.reviews || 0;
  const instructor = course.instructorName || course.instructor || "Unknown";
  const avatar = course.instructorAvatar || "IN";
  
  const discount = course.originalPrice > course.price 
    ? Math.round(((course.originalPrice - course.price) / course.originalPrice) * 100) 
    : 0;

  return (
    <div className="card group overflow-hidden flex flex-col">
      <div className={`relative h-40 bg-gradient-to-br ${course.color || 'from-brand-500 to-purple-600'} flex-shrink-0`}>
        <div className="absolute inset-0 flex flex-col justify-end p-4">
          <span className="badge bg-white/20 text-white text-xs w-fit mb-2 uppercase">{course.category}</span>
          <span className="text-white/80 text-xs">{course.level} Level</span>
        </div>
        {discount > 0 && (
          <div className="absolute top-3 right-3 bg-red-500 text-white text-xs font-bold px-2 py-1 rounded-lg">
            {discount}% OFF
          </div>
        )}
      </div>

      <div className="p-5 flex flex-col flex-1">
        <h3 className="font-semibold text-gray-900 leading-snug mb-2 line-clamp-2 group-hover:text-brand-600 transition-colors">
          {course.title}
        </h3>

        <div className="flex items-center gap-2 mb-3">
          <div className="w-6 h-6 bg-brand-100 rounded-full flex items-center justify-center flex-shrink-0">
            <span className="text-brand-600 text-xs font-bold">{avatar.slice(0,2).toUpperCase()}</span>
          </div>
          <span className="text-sm text-gray-500 truncate">{instructor}</span>
        </div>

        <div className="flex items-center gap-4 text-xs text-gray-400 mb-4">
          <span className="flex items-center gap-1"><Clock className="w-3.5 h-3.5" /> {course.duration}</span>
          <span className="flex items-center gap-1"><BookOpen className="w-3.5 h-3.5" /> {course.totalModules || "0"} modules</span>
          <span className="flex items-center gap-1"><Users className="w-3.5 h-3.5" /> {students.toLocaleString()}</span>
        </div>

        <div className="flex items-center gap-1.5 mb-4">
          <div className="flex">
            {[1,2,3,4,5].map(i => (
              <Star key={i} className={`w-3.5 h-3.5 ${i <= Math.round(rating) ? "text-gold-500 fill-gold-500" : "text-gray-200"}`} />
            ))}
          </div>
          <span className="text-xs font-semibold text-gray-700">{rating}</span>
          <span className="text-xs text-gray-400">({reviews} reviews)</span>
        </div>

        <div className="flex-1" />

        <div className="flex items-center justify-between pt-3 border-t border-surface-100">
          <div>
            <span className="text-lg font-bold text-gray-900">₹{course.price?.toLocaleString()}</span>
            {course.originalPrice && (
              <span className="text-xs text-gray-400 line-through ml-1.5">₹{course.originalPrice?.toLocaleString()}</span>
            )}
          </div>
          <Link
             to={ROUTES.COURSE_DETAIL(id)} // Use the helper function from your routes file!
             className="flex items-center gap-1 text-sm font-semibold text-brand-600 hover:text-brand-700 group/btn"
          >
           View <ArrowRight className="w-4 h-4 group-hover/btn:translate-x-0.5 transition-transform" />
         </Link>
        </div>

        {course.enrolled && (
          <div className="mt-3">
            <div className="flex justify-between text-xs text-gray-400 mb-1">
              <span>Progress</span>
              <span className="text-brand-600 font-medium">{course.progress || 0}%</span>
            </div>
            <div className="progress-bar">
              <div className="progress-fill" style={{ width: `${course.progress || 0}%` }} />
            </div>
          </div>
        )}
      </div>
    </div>
  );
}