import React from "react";
import { Link } from "react-router-dom";
import { Star, Clock, Users, BookOpen, ArrowRight } from "lucide-react";

export default function CourseCard({ course }) {
  // Use the ID generated by the Safety Mapper
  const id = course?._id || course?.id;
  
  // Safety Mappers
  const students = course?.totalStudents || course?.students || 0;
  const rating = course?.averageRating || course?.rating || 0;
  const reviews = course?.totalReviews || course?.reviews || 0;
  const price = course?.price || 0;
  
  // Safely handle instructor name and extract initials
  const instructor = course?.instructor?.fullName || course?.instructorName || course?.instructor || "Expert Instructor";
  const avatar = course?.instructorAvatar || (typeof instructor === 'string' ? instructor.split(" ").map(n => n[0]).join("").substring(0, 2).toUpperCase() : "IN");
  const category = course?.category || "General";
  
  const discount = course?.originalPrice > price 
    ? Math.round(((course.originalPrice - price) / course.originalPrice) * 100) 
    : 0;

  return (
    <div className="card group overflow-hidden flex flex-col h-full bg-white border border-surface-200 rounded-2xl hover:shadow-md transition-all">
      <div className={`relative h-40 bg-gradient-to-br ${course?.color || 'from-brand-500 to-purple-600'} flex-shrink-0`}>
        <div className="absolute inset-0 flex flex-col justify-end p-4">
          <span className="badge bg-white/20 text-white text-xs w-fit mb-2 uppercase font-bold px-3 py-1 rounded-full backdrop-blur-sm">
            {category}
          </span>
          <span className="text-white/90 text-xs font-medium">{course?.level || "Beginner"} Level</span>
        </div>
        {discount > 0 && (
          <div className="absolute top-3 right-3 bg-red-500 text-white text-xs font-bold px-2 py-1 rounded-lg">
            {discount}% OFF
          </div>
        )}
      </div>

      <div className="p-5 flex flex-col flex-1">
        <h3 className="font-bold text-gray-900 text-lg leading-snug mb-3 line-clamp-2 group-hover:text-brand-600 transition-colors">
          {course?.title || "Untitled Course"}
        </h3>

        {/* INSTRUCTOR + DYNAMIC CATEGORY LABEL */}
        <div className="flex items-center gap-3 mb-4">
          <div className="w-8 h-8 bg-brand-100 rounded-full flex items-center justify-center flex-shrink-0">
            <span className="text-brand-600 text-xs font-bold">{avatar}</span>
          </div>
          <div>
            <span className="text-sm font-semibold text-gray-700 block truncate">{instructor}</span>
            <span className="text-xs text-gray-500 block">{category} Expert</span>
          </div>
        </div>

        <div className="flex items-center gap-4 text-xs text-gray-500 mb-4">
          <span className="flex items-center gap-1"><Clock className="w-4 h-4" /> {course?.duration || "0 hrs"}</span>
          <span className="flex items-center gap-1"><BookOpen className="w-4 h-4" /> {course?.totalModules || course?.modules?.length || "0"} modules</span>
          <span className="flex items-center gap-1"><Users className="w-4 h-4" /> {students.toLocaleString()}</span>
        </div>

        <div className="flex items-center gap-1.5 mb-4">
          <div className="flex">
            {[1,2,3,4,5].map(i => (
              <Star key={i} className={`w-4 h-4 ${i <= Math.round(rating) ? "text-amber-400 fill-amber-400" : "text-gray-200"}`} />
            ))}
          </div>
          <span className="text-sm font-bold text-gray-700 ml-1">{rating}</span>
          <span className="text-xs text-gray-400">({reviews} reviews)</span>
        </div>

        <div className="flex-1" />

        <div className="flex items-center justify-between pt-4 border-t border-surface-100 mt-2">
          <div>
            <span className="text-xl font-black text-gray-900">
              {price === 0 ? "Free" : `₹${price.toLocaleString()}`}
            </span>
            {course?.originalPrice && (
              <span className="text-sm text-gray-400 line-through ml-2">₹{course.originalPrice?.toLocaleString()}</span>
            )}
          </div>
          
          {/* 🔥 FIX 404: Direct path mapping to match AppRoutes perfectly */}
          <Link
             to={`/course/${id}`} 
             className="flex items-center gap-1 text-sm font-bold text-brand-600 hover:text-brand-700 group/btn"
          >
            View <ArrowRight className="w-4 h-4 group-hover/btn:translate-x-1 transition-transform" />
          </Link>
        </div>

        {course?.enrolled && (
          <div className="mt-4 pt-3 border-t border-surface-100">
            <div className="flex justify-between text-xs text-gray-500 mb-1.5">
              <span>Progress</span>
              <span className="text-brand-600 font-bold">{course.progress || 0}%</span>
            </div>
            <div className="w-full bg-surface-100 rounded-full h-2">
              <div className="bg-brand-500 h-2 rounded-full transition-all" style={{ width: `${course.progress || 0}%` }} />
            </div>
          </div>
        )}
      </div>
    </div>
  );
}